version: '3.8'

services:
  watcher:
    build:
      context: ./TheWatcherGo
      dockerfile: Dockerfile
    container_name: the-watcher-app
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    networks:
      - sss4g8gkwk80cw8kk888sgo4
networks:
  sss4g8gkwk80cw8kk888sgo4:
    external: true
